### ISSUE TITLE
on-key-pressed and on-key-released documentation

### ISSUE THREAD

**Issue by hasn0life** [soegaard/sketching#29]
I believe events [on-key-pressed](https://soegaard.github.io/sketching/Reference.html#%28part._on-key-pressed%29) and [on-key-released](https://soegaard.github.io/sketching/Reference.html#%28part._on-key-released%29) are usable in conjunction with [key](https://soegaard.github.io/sketching/Reference.html#%28def._%28%28lib._sketching%2Fexports-no-gui..rkt%29._key%29%29) variable, as the [analogous processing docs](https://processing.org/reference/keyReleased_.html) indicate. This isn't mentioned in their documentation, but this info is necessary when working with these events.

**Comment by soegaard** [comment]
I added a related paragrah that links to `on-key-pressed` and `on-key-released`.

Thanks.

**Comment by soegaard** [comment]
@all-contributors please add @hasn0life for documentation
