### ISSUE TITLE
Export as SVG?

### ISSUE THREAD

**Issue by DarrenN** [soegaard/sketching#35]
I'm interested in using this to generate SVGs for a plotter. I dug around in both `gui.rkt` and `sketching-canvas%` and it looks like everything is rendered to a `%bitmap`. Is there a way to save a rendered sketch to SVG? The best I could do was inject the bitmap into an `svg-dc%`.

**Comment by soegaard** [comment]
Hi Darren,

Sounds like a great project using Sketching to make drawings for a plotter.

Below is an example of how an one-frame drawing can be saved as an svg.

`#lang sketching
(require (only-in racket/draw svg-dc%)
         (only-in sketching/parameters current-dc))

(define WIDTH  200)
(define HEIGHT 200)
(define OUTPUT "my-svg.svg")



(define (setup)
  (no-loop)
  (size WIDTH HEIGHT))


(define (draw)
  ; create a new svg
  (define an-svg-dc
    (new svg-dc%
         [width  width]
         [height height]
         [output OUTPUT]
         [exists 'replace])) ; overwrite existing file

  ; An svg is a document with a series of pages
  (an-svg-dc.start-doc "My Drawing")
  (an-svg-dc.start-page)

  ; tell sketching to draw to the svg drawing context
  (current-dc an-svg-dc)
  
  (rect-mode 'center)
  (translate 100 100) ; place the center in (100,100)
  (square 0 0 50)
  (line -25 25 25 -25)

  ; end page and document (saves it)
  (an-svg-dc.end-page)
  (an-svg-dc.end-doc))

`

The drawing model in Sketching is pixel based though, so I am reluctant to add a vector drawing mode to the api.

**Comment by DarrenN** [comment]
Thanks for this, much appreciated! I think this will get me most of the way. 

FWIW I've been using a combo of `2htdp/image` and `Metapict` to output SVGs. I'm also requiring chunks of `Metapict` into `#lang sketching` to get the point (`pt`) and vector (`vec`) support functions.

**Comment by soegaard** [comment]
I forgot to use `(no-gui)` in `setup`. Calling `(no-gui)` means the window won't show.
