### ISSUE TITLE
Error message when using #lang sketching without further definitions

### ISSUE THREAD

**Issue by dubst3pp4** [soegaard/sketching#45]
Hello,

thanks for this great project. I wanted to play with sketching, but get an error message when I put `#lang sketching` into DrRackets definition window without further definitions:

Definitions window:

```scheme
#lang sketching
```

Interactions window:

```
../../usr/share/racket/pkgs/errortrace-lib/errortrace/stacktrace.rkt:690:2: car: contract violation
  expected: pair?
  given: '()
```

When I put one of the provided examples into the definitions and run it, there is no such error. 

I'm using Racket 8.3 [cs] and installed sketching via `raco pkg install sketching`.

Sorry if it is just a beginners mistake, as I'm not experienced neither with sketching nor with Racket.

Best regards,
Marc

**Comment by soegaard** [comment]
Hi Marc,

Thanks for letting me know. This is clearly a bug in Sketching.
I must never have tried that.

I'll look into it.

Best Regards,
Jens Axel

**Comment by dubst3pp4** [comment]
Thanks for having a look :+1: :slightly_smiling_face:

**Comment by soegaard** [comment]
Hi,

I commited a fix. If there are no definitions or expressions at all a little message is printed that points to the examples.

Thanks for the report.

**Comment by dubst3pp4** [comment]
Thank you very much!
