### ISSUE TITLE
unhex uses base 2 instead of base 16

### ISSUE THREAD

**Issue by eXodiquas** [soegaard/sketching#63]
While playing around with some functions I found out that `unhex` is not behaving as it should. It treats the input as base 2 instead of base 16.

**Comment by eXodiquas** [comment]
Fixing this is trivial, so I did it. 
But I don't know if I have to change something for the documentation because my pull requests always fail the workflow runs.

**Comment by soegaard** [comment]
I need to look at the automatic workflow.

Currently it both builds the documentation and copies to soegaard.github.io.
Presumably the documentation build fine.
I am guessing, the error you see is a permission error - Github allows only
me to actually copy the resulting html files to soegaard.github.io.

I'll need to change the workflow, so it just builds the documentation.
And then make a new workflow, that only copies.

Thanks for finding the error.

**Comment by soegaard** [comment]
If you click on the check, you will see:

![image](https://user-images.githubusercontent.com/461765/150555946-ae2c8b84-75dc-45b9-9d10-42d6a0b62a2e.png)

Only the deploy (copying) step failed, so your fix is fine.
