### ISSUE TITLE
maximum stroke-weight is 255

### ISSUE THREAD

**Issue by ericcervin** [soegaard/sketching#79]
was adapting the simple drawing program below. i get an error whenever the stroke-weight is set to over 255.

`#lang sketching
(define (setup)
  (size 480 120)
  (smoothing 'smoothed)
  (background 200)

  (stroke 0 102)
  (set-frame-rate! 60)
  )

(define (draw)
   (stroke-weight (dist mouse-x mouse-y pmouse-x pmouse-y))
   (line mouse-x mouse-y pmouse-x pmouse-y)
)
`

**Comment by ericcervin** [comment]
![image](https://user-images.githubusercontent.com/1158978/157162948-93c20e67-d664-42a7-97ec-14a9abdbab67.png)

**Comment by ericcervin** [comment]
![image](https://user-images.githubusercontent.com/1158978/157163171-70ef1f60-b111-4a40-8fa4-746f668bae9b.png)

**Comment by ericcervin** [comment]
![image](https://user-images.githubusercontent.com/1158978/157163441-b890731a-3427-41c7-a857-d952e1b02015.png)

**Comment by soegaard** [comment]
Hi,

Thanks for finding this. Racket's drawing library currently has a maximum pen width of 255.
I am not sure why.

The example program can be fixed by:

    (define (draw)
        (stroke-weight (min 255 (dist mouse-x mouse-y pmouse-x pmouse-y)))
         (line mouse-x mouse-y pmouse-x pmouse-y))
         
However Skeching should expose the error from the underlying layer.
I am inclined to let Sketching silently limit the stroke weight to 255 rather than throwing an error.

I'll ask around to see if the limit of 255 is a hard limit or not.

**Comment by ericcervin** [comment]
Thanks. I decided that **confine** was more my style.

`
(define (draw)
   (stroke-weight (constrain (dist mouse-x mouse-y pmouse-x pmouse-y) 0 255))
   (line mouse-x mouse-y pmouse-x pmouse-y)
)
`

Whatever combination of documentation and error handling that you use, it shouldn't feel broken when someone naively ports a program from java Processing. Silently constraining the stroke-weight seems fine

**Comment by ericcervin** [comment]
No idea why the formatting in my code got so blown up. I tried it a few times.

**Comment by soegaard** [comment]
Hi.

I have committed a fix that clamps the width to [0;255].

Thanks for finding the issue.

I still haven't figured out why there is a limit of 255.

**Comment by ericcervin** [comment]
OK. I'm trying to be smart enough to update directly from github and failing

![image](https://user-images.githubusercontent.com/1158978/157525908-1e99817b-5bff-4a90-8354-30a064409f1e.png)

**Comment by soegaard** [comment]
I forgot manually to  get the package server to rescan the github repo.
I think it does it automatically once or twice a day.
Anyways, I have made it rescan the repo, so I hope it picks up the changes now.

The commit you want is:

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/461765/157527891-9130355e-f255-4c04-985e-59b5334e6a8b.png">

**Comment by ericcervin** [comment]
```
(define (draw)
   (stroke-weight (dist mouse-x mouse-y pmouse-x pmouse-y))
   (line mouse-x mouse-y pmouse-x pmouse-y)
)
```

OK. The only trick was updating my DrRacket from 8.2 -> 8.4 . Now the above works great
